apiVersion: v2
name: my-chart
description: A Helm chart example with dependencies
version: 0.1.0

dependencies:
  - name: nginx
    version: 1.2.1
    repository: https://example.com/charts
  - name: redis
    version: 2.0.1
    repository: https://example.com/charts
  - name: mariadb
    version: 3.5.1
    repository: https://example.com/charts
