gitops-runtime:
  global:
    codefresh:
      accountId: 6594ee8b625ab0ff9a663c88
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: myruntime
