run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      source_env:
        type: choice
        description: 'Source Environment'
        options:
        - lab-a
        - lab-b
        - lab-c
        required: true
      destination_env:
        type: choice
        description: 'Destination Environment'
        options:
        - prod
        - prod-pilot
        required: true
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is approved
        run: echo "User ${{ github.actor }} approved the workflow"
    


