name: Copy Helm Repo and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder within env'
        required: true
      destination-folder:
        description: 'Destination folder within env'
        required: true

jobs:
  copy-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          branch_name="copy-helm-${{ github.run_number }}"
          git checkout -b $branch_name

      - name: Copy Helm repo
        run: |
          cp -r "env/${{ github.event.inputs.source-folder }}"/* "env/${{ github.event.inputs.destination-folder }}/"

      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Copy Helm repo from ${{ github.event.inputs.source-folder }} to ${{ github.event.inputs.destination-folder }}"

      - name: Push changes
        run: git push origin copy-helm-${{ github.run_number }} --set-upstream

      - name: Open the pull request
        run: |
          gh pr create \
          -B main \
          --title "Auto generated PR" \
          --body "PR raised automatically through workflow"
        env:
          GH_TOKEN: ${{ github.token }}

