name: Copy Helm Repo and Create Pull Request

on:
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Source folder within env'
        required: true
      destination-folder:
        description: 'Destination folder within env'
        required: true

jobs:
  copy-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          git checkout -b copy-helm-${{ github.run_number }}
      
      - name: Copy Helm repo
        run: |
          mkdir -p destination
          cp -r "env/${{ github.event.inputs.source-folder }}"/* "env/${{ github.event.inputs.destination-folder }}/"
      
      - name: Commit changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add .
          git commit -m "Copy Helm repo from ${{ github.event.inputs.source-folder }} to ${{ github.event.inputs.destination-folder }}"

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: copy-helm-${{ github.run_number }}
      - name: Push changes
        run: git push origin copy-helm-${{ github.run_number }} --set-upstream
        
      - name: Fetch main branch
        run: git fetch origin main

      - name: Hard reset to main branch
        run: git reset --hard origin/main

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: copy-helm-${{ github.run_number }}
          base: master
          title: "Copy Helm Repo and Create Pull Request"
          body: "This pull request was automatically created to copy the Helm repo from ${{ github.event.inputs.source-folder }} to ${{ github.event.inputs.destination-folder }}."
