name: Print Repository and Tag Matrix

on: workflow_dispatch


jobs:
  print_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository_tag: ["repo1:tag1", "repo2:tag2"]

    steps:
      - name: Print Repository and Tag
        run: |
          for item in "${{ matrix.repository_tag }}"; do
            repository=$(echo $item | cut -d ":" -f 1)
            tag=$(echo $item | cut -d ":" -f 2)
            echo "Repository: $repository, Tag: $tag"
          done
          echo "${repository_tag[@]}"

