name: choice workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
      source-folder:
        type: choice
        description: Make a choice
        options:
        - dev
        - prod
        - lab
      destination-folder:
        type: choice
        description: Make a choice
        options:
        - prod-pilot
        - prod
        - prod
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "boolean is ${{ github.event.inputs.boolean }}" / ${{ inputs.boolean }} 
          echo  "env/${{ github.event.inputs.source-folder }} env/${{ github.event.inputs.destination-folder }}/"
