name: list parsing

on:
  workflow_dispatch

jobs:
  copy_docker_image:
    name: Copy Docker Image
    runs-on: ubuntu-latest
    outputs:
      repository_tag_list: ${{ steps.set-repo-tag-list.outputs.repository_tag_list }}
    steps:
      - name: Set Repository Tag List
        id: set-repo-tag-list
        run: |
          repository_tag_list=("docker.artifactory.com/sample-co/xapp:v0.0.1" "docker.artifactory.com/sample-co/ydec:v0.0.2")
          echo "repository_tag_list=${repository_tag_list[*]}" >> $GITHUB_ENV
          
  next_step:
    name: Promote Container Image
    runs-on: ubuntu-latest
    needs: [copy_docker_image]
    steps:
      - name: Parse Repository Tag List
        run: |
          repository=$(echo ${{ matrix.repository_tag_list }} | cut -d ":" -f 1)
          tag=$(echo ${{ matrix.repository_tag_list }} | cut -d ":" -f 2)

          echo "Promoting $repository with tag $tag into next environment"

          # Promoting the image
          - name: Promote Container Image
            id: promote-image
            # uses: 
            run: |
              # repository: $repository
              # image_tag: $tag
              echo "repository: $repository"  # Echo repository value
              echo "image_tag: $tag"          # Echo image_tag value


# name: Colored Output Example

# on: workflow_dispatch

# jobs:
#   example:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up repository
#         uses: actions/checkout@v2

#       - name: Print colored text
#         run: |
#           echo -e "\e[32mThis is green text\e[0m"
#           echo -e "\e[33mThis is yellow text\e[0m"
#           echo -e "\e[31mThis is red text\e[0m"
