name:  list parsing

on: workflow_dispatch

jobs:
  copy_docker_image:
    name: Copy Docker Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-repo-tag-list.outputs.repository_tag_list }}
    steps:
      - name: Set Repository Tag List
        id: set-repo-tag-list
        run: |
          repository_tag_list=("docker.artifactory.com/sample-co/xapp:v0.0.1" "docker.artifactory.com/sample-co/ydec:v0.0.2")
          repository_tag_json=$(echo "${repository_tag_list[@]}" | jq -nR '[inputs | {repository_tag: .}]' | jq -s '')
          echo "repository_tag_list=$repository_tag_json" >> $GITHUB_OUTPUT
        

  # next_step:
  #   name: Promote Container Image in Dev Environment
  #   runs-on: ubuntu-latest
  #   needs: [copy_docker_image]
  #   strategy:
  #     matrix:
  #       repository_tag: ${{fromJson(needs.copy_docker_image.outputs.repository_tag_list)}}

  #   steps:
  #     - name: Print Repository and Tag
  #       run: |
  #         for item in "${matrix.repository_tag[@]}"; do
  #           repository_tag=$(echo "$item" | jq -r '.repository_tag')
  #           echo "Repository and Tag: $repository_tag"
  #         done



# name: Colored Output Example

# on: workflow_dispatch

# jobs:
#   example:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Set up repository
#         uses: actions/checkout@v2

#       - name: Print colored text
#         run: |
#           echo -e "\e[32mThis is green text\e[0m"
#           echo -e "\e[33mThis is yellow text\e[0m"
#           echo -e "\e[31mThis is red text\e[0m"
