name: Colored Output Example

on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v2

      - name: Print colored text
        run: |
          echo -e "\e[32mThis is green text\e[0m"
          echo -e "\e[33mThis is yellow text\e[0m"
          echo -e "\e[31mThis is red text\e[0m"
